name: RestCI to Docker Hub

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
    # - run: npm run test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub 
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Build the tagged Docker image
        run: docker build -t eliheuman/pro_restaurant
      - name: Push the tagged Docker image
        run: docker push eliheuman/pro_restaurant

  
